### ISSUE TITLE
Cookie 'domain' mismatch

### ISSUE THREAD

**Issue by IcySnex** [gladiatortoise/node-apiless-youtube-upload#25]
InvalidCookieDomainError: invalid cookie domain: Cookie 'domain' mismatch

![image](https://user-images.githubusercontent.com/81762750/117856792-5bc90b80-b28c-11eb-86da-4135012412c0.png)

**Comment by RodriguesCosta** [comment]
same here

**Comment by acedigibits** [comment]
In uploadVideo.js change line  await driver.get(GOOGLE_URL); to  await driver.get(YOUTUBE_URL); where YOUTUBE_URL = "https://youtube.com/";
