### ISSUE TITLE
Upload page gets reached then closes out.

### ISSUE THREAD

**Issue by firsttobebear** [gladiatortoise/node-apiless-youtube-upload#3]
During the checkCookiesValidity function, it nearly makes it to the end opening up the upload page but then closing out of it then erroring.

`(node:3772) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received undefined
    at Object.open (fs.js:443:10)
    at writeFile (fs.js:1446:6)
    at go$writeFile (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\graceful-fs\graceful-fs.js:139:14)
    at writeFile (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\graceful-fs\graceful-fs.js:136:12)
    at C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\node-apiless-youtube-upload\node_modules\universalify\index.js:10:14
    at new Promise (<anonymous>)
    at writeFile (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\node-apiless-youtube-upload\node_modules\universalify\index.js:7:14)
    at Object._writeFile (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\node-apiless-youtube-upload\node_modules\jsonfile\index.js:68:48)
    at Object._writeFile (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\node-apiless-youtube-upload\node_modules\universalify\index.js:21:45)
    at Object.exports.default [as saveCookiesToDisk] (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\node-apiless-youtube-upload\dist\methods\saveCookiesToDisk.js:8:30)
    at Timeout._onTimeout (C:\Users\risha\Documents\Twitch Vod Downloader\server.js:1276:27)`

I have node version v14.15.4 and have the chrome web browser. Are you able to replicate this?

**Comment by gladiatortoise** [comment]
Hi! This error just tells me there was no path argument provided to saveCookiesToDisk() or it was undefined. Can you please provide the code you're using?

**Comment by firsttobebear** [comment]
The code that I am running is

`setTimeout(async function() {
    const youtubeUploader = require("node-apiless-youtube-upload")

    await youtubeUploader.promptLoginAndGetCookies()
    
    if (await youtubeUploader.checkCookiesValidity()) {
        console.log("Uploading video")
        await youtubeUploader.uploadVideo({
            videoPath: 'FinishedVod.mp4',
            title: '📡 Automatically Uploaded Video 📡',
            description: 'This is a placeholder description.',
            visibility: 'unlisted',
            monetization: false
        })
    }

    await youtubeUploader.saveCookiesToDisk(process.cwd() + '/cookies_saved.json')

    await youtubeUploader.loadCookiesFromDisk(process.cwd() + '/cookies_saved.json')
})`

It errors before being able to save it and does it before it can upload the video.

**Comment by gladiatortoise** [comment]
My interpretion is that ```await youtubeUploader.checkCookiesValidity()```  resolves to false, and therefore the whole upload block is ignored. Then ```process.cwd() + '/cookies_saved.json'``` (for some reason) resolves to ```undefined```. These would be separate problems.

Was the login (in chrome window) succesfull? It should first open chrome twice, once for login and once for brand account selection.

**Comment by firsttobebear** [comment]
Yes the account selection was successful. It made me sign in, then closed out of chrome then opened chrome again to youtube.

**Comment by gladiatortoise** [comment]
Oh I just realized what's happening 😅. ``` const youtubeUploader = require("node-apiless-youtube-upload") ``` doesn't create a new instance, but gives you manual methods. To use the module like in readme.md usage section,  to create a new instance by ``` const youtubeUploaderInstance = new youtubeUploader()```

Then change all the methods from ```youtubeUploader.XXX``` to ```youtubeUploaderInstance.XXX```

**Comment by gladiatortoise** [comment]
Oh I just realized what's happening 😅. const youtubeUploader = require("node-apiless-youtube-upload") doesn't create a new instance, but gives you manual methods. To use the module like in readme.md usage section, you need to create a new instance by ```const youtubeUploaderInstance = new youtubeUploader()``` and then change all the methods from youtubeUploader.XXX to youtubeUploaderInstance.XXX

You can also use this module with the "manual methods", but then it would go like this:
```
var cookies = await youtubeUploader.promptLoginAndGetCookies()

if (await youtubeUploader.checkCookiesValidity(cookies)) {
    await youtubeUploader.uploadVideo({
        /* ... */
    }, cookies)
}

await youtubeUploader.saveCookiesToDisk(cookies, process.cwd() + '/cookies_saved.json')
```

**Comment by firsttobebear** [comment]
When I try to call new on it youtubeUploader it errors.

My code:
`
const youtubeUploader = require("node-apiless-youtube-upload")
const youtubeUploaderInstance = new youtubeUploader()
`

The error:
`(node:8608) UnhandledPromiseRejectionWarning: TypeError: youtubeUploader is not a constructor`

**Comment by gladiatortoise** [comment]
Alright so in CommonJS it would go ```const youtubeUploader = require("node-apiless-youtube-upload").default```

**Comment by firsttobebear** [comment]
The good thing is the issue is fixed but there is another one.

`
Uploading 69% ... 27 seconds left
Uploading 75% ... 23 seconds left
Uploading 81% ... 18 seconds left
Uploading 87% ... 13 seconds left
Uploading 93% ... 9 seconds left
Uploading 98% ... 4 seconds left
Upload complete ... Processing will begin shortly
Publishing..
(node:2404) UnhandledPromiseRejectionWarning: ElementNotInteractableError: element not interactable
  (Session info: headless chrome=88.0.4324.104)
    at Object.throwDecodedError (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\http.js:655:13)
    at Executor.execute (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\http.js:581:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async thenableWebDriverProxy.execute (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\webdriver.js:724:17)
    at async Timeout.<anonymous> (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\node-apiless-youtube-upload\dist\methods\uploadVideo.js:227:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:2404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

This happens as soon as it says "Publishing.."

**Comment by gladiatortoise** [comment]
I encountered this issue once before and I don't know what causes it. Basically the "Done"/"Publish" button is not clickable in some cases.

I createad a new issue for this, as the original one was resolved.
