### ISSUE TITLE
ElementNotInteractableError: element not interactable (probably the "Done" button)

### ISSUE THREAD

**Issue by gladiatortoise** [gladiatortoise/node-apiless-youtube-upload#4]
`
Uploading 69% ... 27 seconds left
Uploading 75% ... 23 seconds left
Uploading 81% ... 18 seconds left
Uploading 87% ... 13 seconds left
Uploading 93% ... 9 seconds left
Uploading 98% ... 4 seconds left
Upload complete ... Processing will begin shortly
Publishing..
(node:2404) UnhandledPromiseRejectionWarning: ElementNotInteractableError: element not interactable
  (Session info: headless chrome=88.0.4324.104)
    at Object.throwDecodedError (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\error.js:517:15)
    at parseHttpResponse (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\http.js:655:13)
    at Executor.execute (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\http.js:581:28)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async thenableWebDriverProxy.execute (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\selenium-webdriver\lib\webdriver.js:724:17)
    at async Timeout.<anonymous> (C:\Users\risha\Documents\Twitch Vod Downloader\node_modules\node-apiless-youtube-upload\dist\methods\uploadVideo.js:227:25)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2404) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 4)
(node:2404) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

This happens as soon as it says "Publishing.."

_Originally posted by @firsttobebear in https://github.com/gladiatortoise/node-apiless-youtube-upload/issues/3#issuecomment-769294626_

**Comment by gladiatortoise** [comment]
I have not yet replicated this issue but I hope I can do it soon enough so I can solve it

**Comment by firsttobebear** [comment]
I have noticed that this only happens when you set the video to unlisted. I am currently setting mine to public and I haven't had any issues publishing.

**Comment by gladiatortoise** [comment]
> I have noticed that this only happens when you set the video to unlisted. I am currently setting mine to public and I haven't had any issues publishing.

This might be just random variation but I'll write it down. For me every visibility options works

**Comment by gladiatortoise** [comment]
On Ubuntu I could replicate this issue by simply using the headless (default) mode. Headfull mode worked as expected.
Then I tried adding ```chromeOptions.windowSize({ width: 1920, height: 1080 })``` with the headless mode and it worked.
I'll add that to the new version and we'll see if the issue comes up again.
