### ISSUE TITLE
How to run Project

### ISSUE THREAD

**Issue by ankitsiliconithub** [gladiatortoise/node-apiless-youtube-upload#5]
can you please tell me How to run Project

**Comment by ankitsiliconithub** [comment]
methods/checkCookiesValidity.ts:2:8 - error TS1192: Module '"/Volumes/SSDApps/Php/Paython/node-apiless-youtube-upload-main 2/node_modules/@types/selenium-webdriver/index"' has no default export.

this kind of error throw

**Comment by gladiatortoise** [comment]
Simply just install it via npm and copy the code at https://github.com/gladiatortoise/node-apiless-youtube-upload#commonjs-simple

Which part are you having problems with?



> why this kind of message display when i try to run file
> (node:20256) ExperimentalWarning: The fs.promises API is experimental

It's just a warning you can ignore. This library uses cutting edge techonlogy😆

**Comment by ankitsiliconithub** [comment]
This kind of error display when i use below link code 
https://github.com/gladiatortoise/node-apiless-youtube-upload#commonjs-simple

Error: Cannot find module 'node-apiless-youtube-upload'

**Comment by gladiatortoise** [comment]
Oh you're right, there was a typo in the example script. It was ```node-apiless-youtube-uploadER```
I updated it now, can you please test if it works for you?

Thanks

**Comment by ankitsiliconithub** [comment]
now this kind of error  display
YoutubeUploader.promptLoginAndGetCookies().then(cookies => {
^

ReferenceError: YoutubeUploader is not defined
    at Object.<anonymous> (/Volumes/SSDApps/Php/Paython/Tsst/test.js:3:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

**Comment by gladiatortoise** [comment]
Oh my god. Another typo.. Now it should be 100% fine.
Should have tested it before commiting 😑😑

**Comment by ankitsiliconithub** [comment]
it's work fine now how to set tags can you please help me

**Comment by gladiatortoise** [comment]
Tags are not supported atm, and I don't know if I will add support. Youtube has said that tags are negligible in video ranking. More info: https://www.socialvideoplaza.com/en/articles/youtube-tags

**Comment by ankitsiliconithub** [comment]
ok but code not working may be when you have multiple channel in your account nothing happen just login select channel  and nothing happen 
this kind of message display
(node:22818) ExperimentalWarning: The fs.promises API is experimental
Removing temp profile from previous run /var/folders/dj/qpf_pjmd3_s4qd9qbryrk6v80000gn/T/node-apiless-youtube-upload-FIpUX9

**Comment by gladiatortoise** [comment]
It should work like this:
1. Login window opens
2. After logging in, Youtube Studio opens and it lets you select an account
3. Window closes. After about 4 sec a new one opens, to finally let you select the account a second time

When you say "nohting happens", does the browser window close or no? What language is your youtube in?

**Comment by gladiatortoise** [comment]
Oh, you're on linux! Actually on linux you have to close the window manually, because I don't know how to detect browser title on that platform yet.

**Comment by ankitsiliconithub** [comment]
i m using mac but nothing happen after login i close the window but still it stuck nothing happen

**Comment by ankitsiliconithub** [comment]
can you please share me you contact details  i mean mail id or whatsapp

**Comment by gladiatortoise** [comment]
Sure! Email: gladiatortoise@gmail.com

**Comment by ankitsiliconithub** [comment]
i just send invite can you please accept it

**Comment by gladiatortoise** [comment]
Alright I'll make a new issue for the problem you faced.
